### ISSUE TITLE
Add the v1 grammar

### ISSUE THREAD

**Issue by nbargnesi** [OpenBEL/language#1]
Because what's a language specification without a grammar?

**Comment by abargnesi** [comment]
I think we have an EBNF grammar that may be helpful as a reference. The ANTLR-specific grammar with Java action code is not useful for the specification.

**Comment by nbargnesi** [comment]
Disagree; any and all formats are useful. Let's just add everything we've got for the time being.

**Comment by nbargnesi** [comment]
Submitted PR #2 - @abargnesi thoughts?
