### ISSUE TITLE
Long form for fromLoc and toLoc

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/language#11]
The specification does not define the long form for `fromLoc` and `toLoc` functions. For example within a translocation:

``` bel
tloc(HGNC:YFG, fromLoc(GOCC:intracellular), toLoc(GOCC:"cell surface"))
```

Should the specification be updated to include `fromLocation` and `toLocation` as long forms?

**Comment by wshayes** [comment]
Fixed
