### ISSUE TITLE
Looks like BEL2 Language document has bad formatting for pmods

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/language#15]
http://openbel.org/language/version_2.0/bel_specification_version_2.0.html#_protein_modifications

Section: Modification Types Provided in Default BEL Namespace

This looks like the right associations (missing additional synonyms showing in language doc table:
            {"short_name": "Ac", "long_name": "acetylation"},
            {"short_name": "ADPRib", "ADP-ribosylation"},
            {"short_name": "Farn", "farnesylation"},
            {"short_name": "Gerger", "geranylgeranylation"},
            {"short_name": "Glyco", "glycosylation"},
            {"short_name": "Hy", "hydroxylation"},
            {"short_name": "ISG", "long_name": "ISG15-protein conjugation"},
            {"short_name": "Me", "long_name": "methylation"},
            {"short_name": "Me1", "long_name": "mono-methylation"},
            {"short_name": "Me2", "long_name": "di-methylation"},
            {"short_name": "Me3", "long_name": "tri-methylation"},
            {"short_name": "Myr", "long_name": "myristoylation"},
            {"short_name": "Nedd", "long_name": "neddylation"},
            {"short_name": "NGlyco", "long_name": "N-linked glycosylation"},
            {"short_name": "NO", "long_name": "Nitrosylation"},
            {"short_name": "OGlyco", "long_name": "O-linked glycosylation"},
            {"short_name": "Palm", "long_name": "palmitoylation"},
            {"short_name": "Ph", "long_name": "phosphorylation"},
            {"short_name": "Sulf", "long_name": "sulfonation"},
            {"short_name":  "Sumo", "long_name": "SUMOylation"},
            {"short_name": "Ub", "long_name": "ubiquitination"},
            {"short_name": "UbK48", "long_name": "Lysine 48-linked polyubiquitination"},
            {"short_name": "UbK63", "long_name": "Lysine 63-linked polyubiquitination"},
            {"short_name": "UbMono", "long_name": "mono-ubiquitination"},
            {"short_name": "UbPoly", "long_name": "poly-ubiquitination"}

**Comment by cebel** [comment]
Dear wshayes,

I found in 2 different BEL 2.0 specifications for **Modification Types**. 2. seems to be a draft and not valid? 

Here I only compare *Label*.  
1. [BEL 2.0 specification on the openbel webpage](http://openbel.org/language/version_2.0/bel_specification_version_2.0.html#_modification_types_provided_in_default_bel_namespace) you cited. 
```python
lables_1 = {"monomethylation","NGlyco","ubiquitination","NO","ISG","di-methylation","Gerger","Ac","ADPRib","Palm","ubiquitylation","ISG15-protein conjugation","Glyco","Hy","Lysine 63-linked polyubiquitination","ADP-rybosylation","methylation","monoubiquitination","Me2","Ph","sulphur addition","OGlyco","sulphation","trimethylation","Myr","Sulf","SUMOylation","Lysine 48-linked polyubiquitination","Nedd","sulphonation","Farn"}
```
2. [BEL 2.0 specification on the openbel wiki](https://wiki.openbel.org/display/BLVD/Modification+Types+Provided+in+Default+BEL+Namespace)
```python
lables_2 = {"NGlyco","UbMono","NO","ISG","Me1","Gerger","UbK63","Ac","ADPRib","Me","Palm","Me3","Glyco","Hy","UbK48","UbPoly","Me2","Ph","OGlyco","Sumo","Ub","Myr","Sulf","Nedd","Farn"}
```
* [BEL 2.0  Specification in PDF openbel.org](on  http://openbel.org/language/version_2.0/bel_specification_version_2.0.pdf) seems to be the same then in 1.
* [Specification on GIT](https://github.com/OpenBEL/language/blob/master/version_2.0/bel_specification_version_2.0.adoc) also exists.

Which is the "real" specification?

In the examples of the specification I still found **P** as *phosphorylation* which is neither defined in 1. nor in 2.. *Ph* seems to becorrect:
* p(HGNC:GSK3B, pmod(P, S, 9)) =| act(p(HGNC:GSK3B), ma(DEFAULT:kin))
* p(HGNC:CLSPN) => (act(p(HGNC:ATR), ma(DEFAULT:kin)) => p(HGNC:CHEK1, pmod(P)))

I suggest that openBEL should define an EBNF (Extended Backus–Naur form) definition of BEL to avoid future conflicts or misinterpretation also in other parts of the specification.

Best regards
Christian

**Comment by wshayes** [comment]
Hi Christian,

Thanks for catching this:

1.  Removed Wiki draft version (the entire Wiki space)
2. The language documents (asciidocs) on github are the canonical versions.  They are processed into the html and pdf versions on the openbel.org/language pages.
3. I fixed the pmod(P) example to pmod(Ph) as you pointed out.  

I'll direct message you regarding the EBNF idea.

**Comment by cthoyt** [comment]
I would suggest grounding all of these in either GO or SBO terms. I've already assembled the mappings in PyBEL: 

https://github.com/pybel/pybel/blob/4ba6c4ed33bf724297fadd6e5e73c6b02099982d/src/pybel/parser/language.py#L248-L405

https://github.com/pybel/pybel/blob/4ba6c4ed33bf724297fadd6e5e73c6b02099982d/src/pybel/parser/language.py#L429-L442

**Comment by wshayes** [comment]
Added issue in belbio/bel_resources#22 for GO equivalents to DEFAULT namespace for pmod's

One can use any namespace argument in for this, we just provide a default option in the BEL Specification if desired.
