### ISSUE TITLE
Travis CI?

### ISSUE THREAD

**Issue by nbargnesi** [OpenBEL/language#6]
I'd like to see the effect of accepting a PR in the future, I think integrating Travis CI could allow for this. Maintainers could see how the PR changes fare in a Travis build. This may allow the HTML artifact to be created for each PR too.

**Comment by abargnesi** [comment]
:+1:

**Comment by abargnesi** [comment]
Travis CI now runs the `tools/scripts/build-html.sh` script. The exit code of this script determines status of build.

The travis build's log will contain the asciidoc text of the document that failed to convert.

We could explore uploading the adoc/html specification as an artifact in the future. See [Uploading Artifacts on Travis CI](http://docs.travis-ci.com/user/uploading-artifacts/). This may be useful for publishing the specification without needing to run the script.
