### ISSUE TITLE
Uploading documents on Travis CI builds

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/language#7]
See #6 for initial work and discussion.

We may want to upload the specifications after a Travis CI Build. Uploads will be send to an S3 bucket. See [Uploading Artifacts in Travis CI](http://docs.travis-ci.com/user/uploading-artifacts/) for more. It is unclear if artifacts will be uploaded regardless of build status.

This may also make it easier to debug a failed HTML render. Currently you have to copy out the failed asciidoc from the travis build log.

**Comment by wshayes** [comment]
I'd prefer to keep this on Github, but I'd like to see the master branch used for updates and Travis build the documents and copy them into the gh-pages branch.
