### ISSUE TITLE
What is the activity function's return type?

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/language#8]
BEL 1.0 declared _abundance_ as the return type for specific activity types (e.g. _kinaseActivity_). This implies that the following is semantically valid:

``` bel
complex( kin( p(HGNC:JAK2) ) )
```

Given the following function signatures of _kinaseActivity_ and _complexAbundance_:

``` bel
kinaseActivity(F:proteinAbundance)abundance
complexAbundance(F:abundance...)abundance
```

---

Does this hold true for BEL 2.0's general-purpose _activity_ function?

@ncatlett

**Comment by ncatlett** [comment]
`complex( kin( p(HGNC:JAK2) ) )` should NOT be semantically valid. Maybe this is a mistake in the BEL 1.0 implementation?

**Comment by abargnesi** [comment]
Yeah it looks that way. Here was [my experience](https://asciinema.org/a/41086) running this through the BelCheck tool.

Thanks for the clarification. We will make sure to correct the semantics in BEL 1.0 & 2.0 implemented in [OpenBEL/parsers](https://waffle.io/OpenBEL/parsers).

We may want to consider a patch to OpenBEL Framework.

**Comment by abargnesi** [comment]
Added OpenBEL/openbel-framework#67
